In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../../data/processed/diabetic_retinopathy/image_metadata.csv")

In [3]:
df

,id_code,height,width,diagnosis,file_path,blur_score,brightness
0,0024cdab0c1e,224,224,1,..\..\data\raw\diabetic_retinopathy\Mild\0024c...,262.95,66.78
1,00cb6555d108,224,224,1,..\..\data\raw\diabetic_retinopathy\Mild\00cb6...,238.39,65.31
2,0124dffecf29,224,224,1,..\..\data\raw\diabetic_retinopathy\Mild\0124d...,406.80,90.57
3,01b3aed3ed4c,224,224,1,..\..\data\raw\diabetic_retinopathy\Mild\01b3a...,252.08,77.22
4,0369f3efe69b,224,224,1,..\..\data\raw\diabetic_retinopathy\Mild\0369f...,287.19,59.32
...,...,...,...,...,...,...,...
3657,f9156aeffc5e,224,224,3,..\..\data\raw\diabetic_retinopathy\Severe\f91...,135.47,34.86
3658,fb61230b99dd,224,224,3,..\..\data\raw\diabetic_retinopathy\Severe\fb6...,133.34,54.09
3659,fcc6aa6755e6,224,224,3,..\..\data\raw\diabetic_retinopathy\Severe\fcc...,148.21,37.61
3660,fda39982a810,224,224,3,..\..\data\raw\diabetic_retinopathy\Severe\fda...,115.17,45.88
3661,fe0fc67c7980,224,224,3,..\..\data\raw\diabetic_retinopathy\Severe\fe0...,125.40,47.24

# train/test split

In [5]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df,
                               test_size=0.2,
                               stratify=df["diagnosis"],
                               random_state=10
                               )

X_train, X_test = train.drop("diagnosis", axis=1), test.drop("diagnosis", axis=1)
y_train, y_test = train["diagnosis"], test["diagnosis"]

In [10]:
X_train

,id_code,height,width,file_path,blur_score,brightness
3623,c5ba9e455d5e,224,224,..\..\data\raw\diabetic_retinopathy\Severe\c5b...,89.36,37.38
3204,1c4f3aa4df06,224,224,..\..\data\raw\diabetic_retinopathy\Proliferat...,353.86,81.25
2026,62b826899151,224,224,..\..\data\raw\diabetic_retinopathy\No_DR\62b8...,424.95,89.05
2751,c58e5c0c5b33,224,224,..\..\data\raw\diabetic_retinopathy\No_DR\c58e...,381.91,83.30
215,8c2f0f04e1ed,224,224,..\..\data\raw\diabetic_retinopathy\Mild\8c2f0...,225.52,67.16
...,...,...,...,...,...,...
1008,a0a0cd8af5a6,224,224,..\..\data\raw\diabetic_retinopathy\Moderate\a...,213.91,68.70
3313,785777558f05,224,224,..\..\data\raw\diabetic_retinopathy\Proliferat...,120.80,70.92
3088,f431f2e119d7,224,224,..\..\data\raw\diabetic_retinopathy\No_DR\f431...,301.53,48.91
3439,e7d2c2c3b30f,224,224,..\..\data\raw\diabetic_retinopathy\Proliferat...,434.00,71.94
3159,fe0e2dee1834,224,224,..\..\data\raw\diabetic_retinopathy\No_DR\fe0e...,288.87,47.60

## Build a class for dataset

In [ ]:
# !pip install torch torchvision

In [18]:
import torch
torch.__version__

'2.13.0+cpu'

In [19]:
from torch.utils.data import Dataset

class RetinopathyDataset(Dataset):
    
    def __init__():
        pass

    def __len__():
        pass

    def __getitem__():
        pass